language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - AWS_VERSION="~2" TEST_VERSION=2
  - AWS_VERSION="~3" TEST_VERSION=3

before_script:
  - composer install --prefer-source --no-interaction
  - composer require aws/aws-sdk-php:${AWS_VERSION} --prefer-source --no-interaction --update-with-dependencies

script:
  - ./vendor/bin/phpunit tests/V${TEST_VERSION}
